version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm ci
      - npm run lint
      - npm run test
      - npm run build --if-present

artifacts:
  files:
    - '**/*'
  base-directory: dist